name = "muh-theme"
license = "MIT"
licenselink = "https://github.com/mickylindsay/muh-theme/blob/main/LICENSE"
description = "Minimal grubbox-dark theme"

homepage = "https://github.com/mickylindsay/muh-theme"
demosite = "TODO"

tags = ["responsive", "minimal", "dark mode"]
features = []
min_version = "0.41.0"

[author]
  name = "Micky Lindsay"
  homepage = "https://yayylmao.dev"

[original]
  name = "risotto"
  homepage = "https://risotto.joeroe.io/"
  repo = "https://github.com/joeroe/risotto"